package com.jcli.codegen;

import com.jcli.core.CliCommand;
import com.jcli.core.CommandLine;
import com.jcli.core.CommandLineParser;
import com.jcli.core.Logger;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class GenClassCommand implements CliCommand {
    @Override
    public String name() {
        return "class";
    }

    @Override
    public String description() {
        return "Generate Java class file";
    }

    @Override
    public int execute(String[] args) throws Exception {
        CommandLineParser parser = new CommandLineParser("jcli gen class")
                .description("Generate Java class from template")
                .addOption(CommandLineParser.Option.ofValue("n", "name", "Class name"))
                .addOption(CommandLineParser.Option.ofValue("p", "package", "Package name"))
                .addOption(CommandLineParser.Option.ofValue("t", "template", "Template: pojo, service, repository, controller, builder, singleton"))
                .addOption(CommandLineParser.Option.ofValue("o", "out", "Output directory"))
                .addOption(CommandLineParser.Option.ofValue("f", "fields", "Field definitions (name:type,...)"))
                .addOption(CommandLineParser.Option.ofValue("a", "author", "Author name"))
                .addOption(CommandLineParser.Option.of("v", "verbose", "Verbose output"));

        CommandLine cmdLine = parser.parse(args);

        if (cmdLine.shouldShowHelp()) {
            parser.printHelp();
            return 0;
        }

        String className = cmdLine.getOptionValue(parser.getLongOption("name"));
        if (className == null) {
            Logger.error("Class name is required");
            return 1;
        }

        String packageName = cmdLine.getOptionValue(parser.getLongOption("package"), "com.example");
        String template = cmdLine.getOptionValue(parser.getLongOption("template"), "pojo");
        String outDir = cmdLine.getOptionValue(parser.getLongOption("out"), ".");
        String fieldsStr = cmdLine.getOptionValue(parser.getLongOption("fields"));
        String author = cmdLine.getOptionValue(parser.getLongOption("author"), "Generated by JCLI");
        boolean verbose = cmdLine.hasOption(parser.getShortOption("v"));

        if (verbose) {
            Logger.setVerbose(true);
        }

        List<Field> fields = new ArrayList<>();
        if (fieldsStr != null) {
            String[] fieldDefs = fieldsStr.split(",");
            for (String fieldDef : fieldDefs) {
                String[] parts = fieldDef.trim().split(":");
                if (parts.length == 2) {
                    fields.add(new Field(parts[0].trim(), parts[1].trim()));
                }
            }
        }

        String content = generateClass(className, packageName, template, fields, author);

        Path outputDir = Paths.get(outDir);
        if (!outputDir.isAbsolute()) {
            outputDir = Paths.get(System.getProperty("user.dir")).resolve(outputDir);
        }

        Path packageDir = outputDir.resolve(packageName.replace('.', '/'));
        Files.createDirectories(packageDir);

        Path classFile = packageDir.resolve(className + ".java");
        Files.writeString(classFile, content);

        Logger.info("Generated: " + classFile.toAbsolutePath());
        return 0;
    }

    private String generateClass(String className, String packageName, String template, List<Field> fields, String author) {
        StringBuilder sb = new StringBuilder();

        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("/**\n");
        sb.append(" * ").append(className).append("\n");
        sb.append(" *\n");
        sb.append(" * @author ").append(author).append("\n");
        sb.append(" */\n\n");

        sb.append("public class ").append(className);

        switch (template.toLowerCase()) {
            case "pojo":
                sb.append(" {\n\n");
                generatePojoFields(sb, fields);
                generatePojoGettersSetters(sb, className, fields);
                sb.append("}\n");
                break;

            case "service":
                sb.append(" {\n\n");
                sb.append("    public ").append(className).append("() {\n");
                sb.append("    }\n\n");
                sb.append("    // Add service methods here\n");
                sb.append("}\n");
                break;

            case "repository":
                sb.append(" {\n\n");
                sb.append("    public ").append(className).append("() {\n");
                sb.append("    }\n\n");
                sb.append("    // Add repository methods here\n");
                sb.append("}\n");
                break;

            case "controller":
                sb.append(" {\n\n");
                sb.append("    public ").append(className).append("() {\n");
                sb.append("    }\n\n");
                sb.append("    // Add controller methods here\n");
                sb.append("}\n");
                break;

            case "builder":
                sb.append(" {\n");
                generateBuilderPattern(sb, className, fields);
                sb.append("}\n");
                break;

            case "singleton":
                sb.append(" {\n\n");
                generateSingletonPattern(sb, className);
                sb.append("}\n");
                break;

            default:
                sb.append(" {\n\n");
                generatePojoFields(sb, fields);
                generatePojoGettersSetters(sb, className, fields);
                sb.append("}\n");
        }

        return sb.toString();
    }

    private void generatePojoFields(StringBuilder sb, List<Field> fields) {
        for (Field field : fields) {
            sb.append("    private ").append(field.type()).append(" ").append(field.name()).append(";\n");
        }
        sb.append("\n");
    }

    private void generatePojoGettersSetters(StringBuilder sb, String className, List<Field> fields) {
        for (Field field : fields) {
            String capitalizedName = capitalize(field.name());
            
            sb.append("    public ").append(field.type()).append(" get").append(capitalizedName).append("() {\n");
            sb.append("        return ").append(field.name()).append(";\n");
            sb.append("    }\n\n");
            
            sb.append("    public void set").append(capitalizedName).append("(").append(field.type()).append(" ").append(field.name()).append(") {\n");
            sb.append("        this.").append(field.name()).append(" = ").append(field.name()).append(";\n");
            sb.append("    }\n\n");
        }
    }

    private void generateBuilderPattern(StringBuilder sb, String className, List<Field> fields) {
        for (Field field : fields) {
            sb.append("    private ").append(field.type()).append(" ").append(field.name()).append(";\n");
        }
        sb.append("\n");
        
        sb.append("    private ").append(className).append("() {\n");
        sb.append("    }\n\n");
        
        for (Field field : fields) {
            String capitalizedName = capitalize(field.name());
            sb.append("    public ").append(className).append(" ").append(field.name()).append("(").append(field.type()).append(" ").append(field.name()).append(") {\n");
            sb.append("        this.").append(field.name()).append(" = ").append(field.name()).append(";\n");
            sb.append("        return this;\n");
            sb.append("    }\n\n");
            
            sb.append("    public ").append(field.type()).append(" get").append(capitalizedName).append("() {\n");
            sb.append("        return ").append(field.name()).append(";\n");
            sb.append("    }\n\n");
        }
        
        sb.append("    public static Builder builder() {\n");
        sb.append("        return new Builder();\n");
        sb.append("    }\n\n");
        
        sb.append("    public static class Builder {\n");
        sb.append("        private ").append(className).append(" instance = new ").append(className).append("();\n\n");
        
        for (Field field : fields) {
            sb.append("        public Builder ").append(field.name()).append("(").append(field.type()).append(" ").append(field.name()).append(") {\n");
            sb.append("            instance.").append(field.name()).append(" = ").append(field.name()).append(";\n");
            sb.append("            return this;\n");
            sb.append("        }\n\n");
        }
        
        sb.append("        public ").append(className).append(" build() {\n");
        sb.append("            return instance;\n");
        sb.append("        }\n");
        sb.append("    }\n");
    }

    private void generateSingletonPattern(StringBuilder sb, String className) {
        sb.append("    private static ").append(className).append(" instance;\n\n");
        sb.append("    private ").append(className).append("() {\n");
        sb.append("    }\n\n");
        sb.append("    public static ").append(className).append(" getInstance() {\n");
        sb.append("        if (instance == null) {\n");
        sb.append("            instance = new ").append(className).append("();\n");
        sb.append("        }\n");
        sb.append("        return instance;\n");
        sb.append("    }\n\n");
        sb.append("    // Add methods here\n");
    }

    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }

    record Field(String name, String type) {}
}
